### ISSUE TITLE
Add a range of problems of different difficulty

### ISSUE THREAD

**Issue by IsakFalk** [RodEsp/daily-leetcode-bot#1]
Currently the bot only posts one problem and this problem may not fit everyone (too easy, too hard or not a good area for the user). Would it be possible to post one problem from each difficulty?

**Comment by RodEsp** [comment]
Hi @IsakFalk, I think it would be! 

There's already [a GraphQL query](https://github.com/RodEsp/daily-leetcode-bot/blob/main/queries.js#L56) that will retrieve all of the problems leetcode has available, and it can be given a slug (which is one of the tags listed in the tag dropdown [here](https://leetcode.com/problemset/all/)). So it's a matter of writing some code to get some problems with that GraphQL query and decide which ones to use everyday.

I want to add that sometime in the near future but I'm not totally sure when exactly I'll have some time.

**Comment by IsakFalk** [comment]
Sounds good!

**Comment by RodEsp** [comment]
Heya @IsakFalk, I just added https://github.com/RodEsp/daily-leetcode-bot/commit/db94cad10f32ef3485ce08cf3bbf0837d898bd28 which creates Zulip posts that look like this:
![image](https://github.com/RodEsp/daily-leetcode-bot/assets/1084688/a47c48fa-113e-4d1b-93c8-de195c22fa59)

The problems are chosen by picking a topic at random and then a problem from each difficulty in that topic also at random, from the ones found [here](https://www.techinterviewhandbook.org/grind75?mode=all&grouping=topics).

I'd still like to have the bot post some more problems directly from the LeetCode API but hopefully this will make the bot more enjoyable for you for now 🤞🏼

**Comment by IsakFalk** [comment]
This is great! Thank you!
